### ISSUE TITLE
Not an issue - which files should I send to PCBWay?

### ISSUE THREAD

**Issue by Kizuo** [solisted/z80sbc#1]
Hello! I see you have many different versions of the gerber file, which one should be used? Also, is the washer.stl file required? What is it for?

Thank you so much! If I build it, how would I go about running BASIC?

-Kizuo

**Comment by Kizuo** [comment]
Also, what service did you use for getting the custom keycaps? Are the keyboard gerbers included in the repo? And finally, is there a complete parts list for the computer and one for the keyboard?

**Comment by solisted** [comment]
Hello!

> Hello! I see you have many different versions of the gerber file, which one should be used? Also, is the washer.stl file required? What is it for?

You need to compress all files in the folder "gerbers" for the main board (or "kbd_gerbers" for the keyboard) and upload that zip file to PCB vendor of your choice.
Each gerber file represents a copper layer, drill positions and sizes, edge cut outs, silk screen labels and drawing etc. So all of them are needed to manufacture a single board.

Washers are needed for self-tapers that attach main board to the bottom of the enclosure if they are too long. 

> Thank you so much! If I build it, how would I go about running BASIC?

BASIC interpreter needs to be ported to this computer or written from scratch. I have an intent to do it after I finish emulator.

**Comment by solisted** [comment]
> Also, what service did you use for getting the custom keycaps? Are the keyboard gerbers included in the repo? And finally, is there a complete parts list for the computer and one for the keyboard?

I used WASD keyboards to manufacture custom keycaps. Gerber files for the keyboard PCB are in the "kbd_gerbers" folder. For the part list - did not have a chance to work on the complete readme file explaining build process and providing part list with vendor part numbers. Will do that a bit later, but for now part numbers are provided on the mainboard schematic.

**Comment by Kizuo** [comment]
Thanks! This is really cool :)
