### ISSUE TITLE
[QUESTION]: Question about the clock generators

### ISSUE THREAD

**Issue by blackdwarf** [solisted/z80sbc#2]
Hi,

This looks like a wonderful project so I started assembling the BOM based on the schematic and the Gerber files. You can see it on https://octopart.com/bom-tool/Ikcc6Aht. 

However, try as I may, I cannot figure out the 4 clock generating…things, in positions `QG1` to `QG4`. I am used to working with crystals, but these are ICs of some kind and I cannot really figure out what to stick in the BOM to order. 

Can you shed more light on what those are?

Thanks!

**Comment by solisted** [comment]
Hi, thank you!

These parts are 4 pin TTL oscillator/clocks in can or DIP packages (same footprint as 8 PIN DIP but 4 legs only).

For example, 10Mhz 5V TTL clock:
https://www.mouser.com/ProductDetail/ABRACON/ACH-10.000MHZ-EK?qs=D0XpjEo%2FJ5B%2F5Ikyf1ZgSg%3D%3D
Or this one, in 4 PIN DIP package (you can see these in the video):
https://www.digikey.com/en/products/detail/epson/SG-531P-10-0000MC-PURE-SN/7728855
